### ISSUE TITLE
Add Online Business 

### ISSUE THREAD

**Issue by Zunnurayni** [BitcoinCash1/Projects-BCH-Donations#3]
can we include businesses/ Companies that accept BCH or you can spend BCH , That should be online example  Namecheap , you can buy domain using Bitcoincash ..

why 
Most people have no idea these platforms or businesses exist ..

**Comment by melroy89** [comment]
Ah that would be a good idea. So maybe I should split up the list with businesses / projects / websites that accepts donations and if they also allow you to spent bch.

**Comment by Zunnurayni** [comment]
yes Please add the list so we contribute and add up the few businesses / Platforms

**Comment by melroy89** [comment]
Done. Ready for PRs.
